/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:b4cd8c54-aa88-47fe-85d3-a555420f1112",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_Y1ubEZkxR",
    "aws_user_pools_web_client_id": "jgq8h0kro18kf9ib0fjb528gt",
    "oauth": {}
};


export default awsmobile;
